### ISSUE TITLE
Getting Started on development 

### ISSUE THREAD

**Issue by johnmay1** [chkr1011/HA4IoT#4]
Hello,

This is really great project.Good work. I am also a developer and able to run the project on my dev machine (not on raspberrypi) from visual studio by making demo controller as startup project but i am not able to start the webapp. I also want to contribute to this project so it will great if you can provide some guideline to setup project on development machine.

Thanks,
John

**Comment by chkr1011** [comment]
Hi John,
thank you for your feedback. You are welcome supporting this project. I am currently working on a huge change. The whole project is migrated to be based on dependency injection and all functionally wrapped into dedicated services. You can have a look at the "develop" branch. Due to this changes a lot of things have changed but also a lot of things are now better maintainable etc.

If you want to run the SDK on your PC you can use the "Local" controller.  This is a UWP app which also shows a few configured buttons, lamps and sockets. The trace is also shown within the UI. The problem with UWP is network isolation. It is not able to open the web app from the local machine. One workaround which worked for me is to disable the "Windows Firewall" service while debugging. Deactivating the firewall does not work. The directory of the web app is shown in the UI. You just need to copy all files from the web app directory to that target directory. But in the end debugging on a real Raspberry Pi is the best way to test everything according to less CPU power etc. :)

At this time the entire configuration is done in C#. For a very far future I planned to configure everything via an XML file. Until this is possible you may need to create your own local branch with your personal configuration. The "Main" controller is the real configuration of my house and can be used as an example. The "default" controller is an empty one. This controller can start and work but will not show any actuators or sensors.

How do you want to support this project? Are you primary a C# developer or a web developer (HTML, CSS, JavaScript) too? Or do you already have some hardware you want to integrate? Just let me know what you are interested in.

Best regards
Christian

**Comment by johnmay1** [comment]
Hi Christian,
Thanks for information but i am still not able to run webapp after copying it to target directory. Should i copy all three folders "HA4IoT.ManagementApp,HA4IoT.NativeApp and HA4IoT.WebApp" to "../LocalState/App/" ? 

Once i copy how to start webapp ? By directly open "index.html" from file system or via local ip address ?

You have also mentioned it's using "configuration.js" file but i am not able to locate it. 

I am planing to integrate Z-Wave hardware.

Best Regards,
John

**Comment by chkr1011** [comment]
Hi John,
You only need to copy the entire content of the "WebApp" directory to the "LocalState\App" directory. The "ManagementApp" is not completed at this time.

Then you can access the WebApp via "http://localhost/App/Index.html" for example. But this URL should also work from any other device like smartphones or tables (with the real IP). The file "index.html" name is important. 

But there is a problem with network isolation. You need to stop the Windows Firewall service in order to open the web app. Even traffic at the local host is isolated and will not work. Additionally you may need to enable access using the app "Fiddler". Please find more information about this here: http://stackoverflow.com/questions/34589522/cant-see-localhost-from-uwp-app

Z-Wave is cool. I assume a new service for this is a good starting point and a few sets of "Endpoints" which are used in the project as an abstraction layer for the hardware. I can give you more info about this if you like.

Best regards
Christian

**Comment by johnmay1** [comment]
Hi Christian,

Yes i would like to get more information to integrate Z-Wave. 
I have tried every steps but none of them i working for me to start web app. I must be doing something wrong. Enabled loopback from VS and fiddler confirmed it. Disabled firewall and Windows defender but it still not working. I don't have raspberry pi to test it. Open for any suggestions.

Best Regards,
John

**Comment by chkr1011** [comment]
Hi John,
sorry I forgot one important thing :-) The port is 1025 if default branch is used and 55000 if master branch is used. But I recommend the "develop" branch.

Best regards
Christian

**Comment by johnmay1** [comment]
Hi Christian,

Tried that too but it doesn't help. I am clue less now. 

Can you tell me where to look into the code to start debugging ?

Regards,
Hemal

**Comment by chkr1011** [comment]
Hi John,

the HTTPServer class is a good entry point. But the trace at the Local controller should give you some errors if it fails to bind the IP address.

You can also try to open the WebApp from your Smartphone etc. The network isolation for UWP apps is only blocking connections within the same device. Maybe this link gives you more information (but the WebApp does not support Edge currently. Chrome is the best chioce now): https://blogs.msdn.microsoft.com/msgulfcommunity/2015/07/01/how-to-debug-localhost-on-microsoft-edge/

I can't remember all steps I have done. It was very frustrating until I found the solution with disabling the Windows Firewall service :-) Maybe the previous steps are also relevant but I can't remember all of them 😞 

You can also send me the trace messages from the log window.

Best regards
Christian

**Comment by johnmay1** [comment]
Hi Christian,

Finally able to access the web app from mobile device. Thanks for all help. Will start looking at code now.

Regards,
John
